export const LOAD_LIST_ITEMS = 'App/LOAD_LIST_ITEMS';
export const LOAD_LIST_ITEMS_SUCCESS = 'App/LOAD_LIST_ITEMS_SUCCESS';
export const LOAD_LIST_ITEMS_ERROR = 'App/LOAD_LIST_ITEMS_ERROR';
export const SET_PAGE = 'App/SET_PAGE'; 
